# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_auto_20190523_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
