# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_task_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
