# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_auto_20190523_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='service_time',
            field=models.TimeField(),
        ),
    ]
