# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0007_auto_20190523_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-timestamp']},
        ),
    ]
